---
- name: Ensure dependencies are installed.
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - gcc
    - glibc-devel
    - make
    - ncurses-devel
    - openssl-devel
    - autoconf
    - git
    - wget
    - http://downloads.dlang.org/releases/2.x/2.067.1/dmd-2.067.1-0.fedora.x86_64.rpm
    - http://code.dlang.org/files/dub-0.9.23-1.x86_64.rpm
